### PR TITLE
Download Runtime Pack for user architecture (if the launcher have one)

### PR DESCRIPTION
**Pull request by artdeell**

### CODE REVIEW

**Comment by artdeell** [comment]
@longjunyu2

**Comment by gabbosta** [comment]
With aarch64?

**Comment by artdeell** [comment]
No
It just downloads the pack authomatically. As you can see, pthe pack index only contains 32-bit pack.

**Comment by gabbosta** [comment]
#30 when will he solve this?

**Comment by artdeell** [comment]
> #30 when will he solve this?

He said he build it, so we just need to wait.

**Comment by gabbosta** [comment]
Yes

**Comment by gabbosta** [comment]
@longjunyu2 take this commit and add it to the master

**Comment by gabbosta** [comment]
and make the version 0.1.4 plz soon

**Comment by gabbosta** [comment]
@longjunyu2

**Comment by longjunyu2** [comment]
好的，又是一个重大的更新。不过我需要等到5月1日放假，然后再查看你的代码，并决定是否全部加入到项目中。谢谢，在此之前请保持这个提交处于开启状态。

**Comment by gabbosta** [comment]
>He said he build it, so we just need to wait.

That's true?

**Comment by artdeell** [comment]
@longjunyu2

**Comment by lizeyan200711** [comment]
MainActivity.java冲突

**Comment by artdeell** [comment]
Fine.

**Comment by artdeell** [comment]
Ideal waste of time

**Comment by artdeell** [comment]
i left mcina because of this sh#t

**Comment by artdeell** [comment]
like wtf why not merge it before revamping the whole launcher

**Comment by provsalt** [comment]
because hey fuck you and your contribution. we can't care less about reviewing it even after a few months

**Pull request closed without merging**
