### PR TITLE
Readme edit and changelog creation

### PR DESCRIPTION
**Pull request by AyHa1810**
I kept the main readme language as english and I totally translated the Chinese readme to simplified Chinese through Google translator since most of the Chinese readme was in english. I used translator because I am not a Chinese. I created a separate md file for changelog because I felt if newer version were released, then the readme file will become too big to reach to the bottom. And if there's any mistakes in Chinese readme, you can correct it, since I use Google translator for translation.

### CODE REVIEW

**Comment by AyHa1810** [comment]
Any type of translator is not accurate. The most accurate translator is a human! Lol
And I am sorry if I made any mistakes!

**Comment by longjunyu2** [comment]
Thanks for your amazing work. :)

**Review by LainSakura — APPROVED** [review]

**Comment by LainSakura** [comment]
Nice work. And so now you've got enough time for both schoolwork and the project (

**Comment by longjunyu2** [comment]
mcinabox的下一个版本的源代码将要上传到该仓库。改动很大(估计90%的代码完全重写)。但是代码并不完全是功能性代码，我做的一部分是结构性调整，这些调整决定了项目的可扩展能力和维护的难易程度，但是这个过程并不顺利，而且在后来的开发中还要不断纠错完善，这也是为什么此次开发周期较长。实际上现在的代码我仍不满意，但是个人目前能力止足于此，为了这个项目我已经抛弃了编程的学习与研究，有些舍本逐末之感。
  新的版本版本号是0.2.0，功能的更新较大，我就不详细说了。各位比较关心的可能是aarch64的运行库。目前，aarch64运行库的编译已经基本完成(暂缺glfw)，但是在实际测试中，liblwjgl.so(所属lwjgl2.9.3)抛出异常，仍需要调试，因此不会立即放出运行库，但是也不远了。
  为了支持多架构的运行库，mcinabox运行库规范也已升级，支持通过packinfo.json文件设定运行库加载策略和过滤条件，为后续运行库架构扩充提供保证。
  minecraft操作体验方面，mcinabox划分出两个模块(gamecontroller和ckb)。其中gamecontroll旨在提供一套控制模型(后端接口-控制器-输入器)，模型内各项目通过接口进行通信，此外gamecontroller模块已经定义了一套标准控制器和输入器，基于此已经提供了三套控制器类(Virtual,Hardware,Sonsor)实现和九套输入器类实现。ckb即客制化键盘的英文缩写，该模块提供自定义键盘的全部实现，采用MAF模型(Manager,Achieve,Feedback)实现，并通过接口封装出一个输入器接入了gamecontroller模块，同时在前端编辑器中复用。
  另外我要声明一下，MCinaBox项目旨在构建并发展一个适配安卓端的Minecraft Java Edition启动器前端，用于为各种后端提供良好的前端支持。

**Comment by longjunyu2** [comment]
Oh I am sorry that I wrote these words in Chinese.It was because I recognised @LainSakura as the men who created this pull request by mistake... And he is a Chinese... XD
And my Englush is not good too..

**Comment by LainSakura** [comment]
> Oh I am sorry that I wrote these words in Chinese.It was because I recognised @LainSakura as the men who created this pull request by mistake... And he is a Chinese... XD
> And my Englush is not good too.. 

:) It's my fault.

**Comment by longjunyu2** [comment]
> > Oh I am sorry that I wrote these words in Chinese.It was because I recognised @LainSakura as the men who created this pull request by mistake... And he is a Chinese... XD
> > And my Englush is not good too..
> 
> :) It's my fault.

哦，不是这样的。有人能看懂中文最好了，用英文麻烦的一批

**Comment by LegacyGamerHD** [comment]
@longjunyu2  said  i did this with google translate

The source code of the next version of mcinabox will be uploaded to this repository. Great changes (it is estimated that 90% of the code is completely rewritten). But the code is not entirely functional code. Part of what I did was structural adjustments. These adjustments determined the scalability and ease of maintenance of the project. However, this process was not smooth, and it was necessary in the subsequent development. Constantly correcting and improving errors is why this development cycle is longer. In fact, I am still not satisfied with the current code, but my current ability is limited to this. For this project, I have abandoned the study and research of programming, and I feel a little bit of the end.
The version number of the new version is 0.2.0, and the feature update is larger, so I won't go into details. You may be more concerned about the aarch64 runtime library. At present, the compilation of the aarch64 runtime library has been basically completed (glfw is temporarily missing), but in actual testing, liblwjgl.so (owned lwjgl2.9.3) throws an exception and still needs debugging, so the runtime library will not be released immediately, but neither Far.
In order to support multi-architecture runtime libraries, the mcinabox runtime library specifications have also been upgraded to support the setting of runtime library loading strategies and filter conditions through the packinfo.json file, providing guarantee for subsequent runtime library expansion.
In terms of minecraft operation experience, mcinabox is divided into two modules (gamecontroller and ckb). Among them, gamecontroll aims to provide a set of control models (back-end interface-controller-input device), and each item in the model communicates through the interface. In addition, the gamecontroller module has defined a set of standard controllers and input devices, based on which it has been provided Three sets of controllers (Virtual, Hardware, Sonsor) are implemented and nine sets of input devices are implemented. ckb is the English abbreviation of customized keyboard. This module provides all the implementation of customized keyboards. It adopts MAF model (Manager, Achieve, Feedback) to achieve, and encapsulates an input device through the interface to connect to the gamecontroller module, and edit at the front Multiplexing in the device.
In addition, I would like to declare that the MCinaBox project aims to build and develop a Minecraft Java Edition launcher front-end adapted to the Android side to provide good front-end support for various back-ends.

**Comment by LegacyGamerHD** [comment]
> 哦，不是这样的。有人能看懂中文最好了，用英文麻烦的一批

yes it is some hard to translate and to read

**Comment by longjunyu2** [comment]
Maybe in the future, people will jointly promote the universal language, so that there is no need to worry about it.XD

**Comment by AyHa1810** [comment]
@longjunyu2 don't worry, I can translate chinese by myself. And @LegacyGamerHD, thanks for translating, though I could've done it by myself.

I wonder how big is the changes. :)

**Comment by longjunyu2** [comment]
@AyHa1810 The Language files in dev branch changed a lot.And I am organizing language codes from hardcode `Strings` in java and xml files. I will provoide Chinese language support first, and then I will translate them to English by myself. Howeve, my English is not very good, and I will use Baidu translater to help to do that. So it may not be accurate enough and there are mistakes. I hope you can fix these translation problems that I can't solve. 
There are many changes this time, but if the project can enter the periodic maintenance phase, the language changes will be much less.
Thank you for your help.

**Comment by longjunyu2** [comment]
@LegacyGamerHD @AyHa1810 I need some time to orangise the language codes. please wait...

**Comment by AyHa1810** [comment]
@longjunyu2 yeah probably there is some grammatical mistakes in the dev branch.

**Pull request merged**
