### PR TITLE
Fix some important thing

### PR DESCRIPTION
**Pull request by artdeell**
@longjunyu2 Without this line of code, the launcher will just crash if you attempt to import runtime pack. Currently I'm preparing runtime pack auto-download system, it will be in the second commit to my fork.

### CODE REVIEW

**Comment by gabbosta** [comment]
@longjunyu2 plz add this commit and close the apk right away because i want to test these commits

**Comment by gabbosta** [comment]
@longjunyu2

**Comment by artdeell** [comment]
I have pretty much done automatic runtime downloader, but currently it was built with some sh*t and sticks and may crash randomly.

**Comment by artdeell** [comment]
> I have pretty much done automatic runtime downloader, but currently it was built with some sh*t and sticks and may crash randomly.

And also it's hella slow because download buffer is only one megabyte in size.
image

**Comment by gabbosta** [comment]
when will he add this and make the apk soon, I want to play with more than 1 GB of ram soon

**Comment by artdeell** [comment]
> when will he add this and make the apk soon, I want to play with more than 1 GB of ram soon

For now it just downloads a runtime pack if you don't have one. It does not update JVM.

**Comment by artdeell** [comment]
I updated a dialog a little bit, and made it translateable (downloader strings are still not translated, but exist in the translation file.)

**Comment by gabbosta** [comment]
But when I put it to more than 1 GB with the runtime it does not enter the game

**Comment by gabbosta** [comment]
I want to put the maximum memory with more than 1024mb

**Comment by artdeell** [comment]
> But when I put it to more than 1 GB with the runtime it does not enter the game

It's NOT supposed to run with more than 1GB. VM is 32-bit, so it JUST CAN'T ADRESS MORE THAN 1 GIG!

**Comment by LegacyGamerHD** [comment]
@artdeell am working on 64 libs i could not get it working

**Comment by LegacyGamerHD** [comment]
also awesome job :P

**Comment by artdeell** [comment]
> @artdeell am working on 64 libs i could not get it working

@LegacyGamerHD maybe because the launcher itself is 32-bit?

**Comment by LegacyGamerHD** [comment]
yeah could be yes

**Comment by artdeell** [comment]
> yeah could be yes
gl4es definitely works in 64-bit
openal... well, it loads, but there's no sound.
lwjgl needs rebuild

**Comment by artdeell** [comment]
@LegacyGamerHD
can u send me ur logcat?

**Comment by LegacyGamerHD** [comment]
Tbh I don't think it's launcher it's me probely that cant code or I do something wrong so I will let some one else do it

**Comment by artdeell** [comment]
> Tbh I don't think it's launcher it's me probely that cant code or I do something wrong so I will let some one else do it

@LegacyGamerHD did you build openjdk 8 for 64bit? if you did, you can just leave all binaries be 32-bit, because binary compartiblity.

**Comment by LegacyGamerHD** [comment]
That's were I struggle 😅

**Comment by artdeell** [comment]
> That's were I struggle 😅

I was struggling at it too

**Comment by artdeell** [comment]
Because that shitty autoconf that they use isn't suited for android

**Comment by LegacyGamerHD** [comment]
Are using this one https://github.com/AdoptOpenJDK/openjdk-aarch64-jdk8u @longjunyu2  said I got do this one

**Comment by artdeell** [comment]
@LegacyGamerHD did U tried this:
https://openjdk.java.net/projects/aarch64-port/

**Comment by LegacyGamerHD** [comment]
No not yet

**Comment by artdeell** [comment]
> No not yet

@LegacyGamerHD don't try, don't waste your time

**Comment by LegacyGamerHD** [comment]
Did you try that ?

**Comment by LegacyGamerHD** [comment]
Ok?

**Comment by artdeell** [comment]
> Did you try that ?

@LegacyGamerHD yes I tried

**Comment by artdeell** [comment]
> > Did you try that ?
> 
> @LegacyGamerHD yes I tried

@LegacyGamerHD it just fails to chech the C compiler because android gcc requires to set sysroot

**Comment by gabbosta** [comment]
I wanted to play with a maximum memory of 1550 mb so the game doesn't close on its own

**Comment by gabbosta** [comment]
How to put these new commits in the apk

**Comment by gabbosta** [comment]
@artdeel Send here a link to the modification you made in mcinabox, both the runtime in the application itself, and the apk with jdk8 aarch64 plz

**Comment by artdeell** [comment]
> @artdeel Send here a link to the modification you made in mcinabox, both the runtime in the application itself, and the apk with jdk8 aarch64 plz

I didn't built JDK8

**Comment by gabbosta** [comment]
#111 so the end of it is about what?

**Comment by gabbosta** [comment]
But still send the link to this apk plz

**Comment by longjunyu2** [comment]
I have built the aarch64 openjdk8 . but did  not update the source yet.

**Comment by gabbosta** [comment]
Since it's been a month since you did this because you don't make it available to all of us? @longjunyu2

**Pull request merged**
