### PR TITLE
Allow installation of Runtime Packs from anywhere.

### PR DESCRIPTION
**Pull request by artdeell**
Read the commits' descriptions.

### CODE REVIEW

**Comment by gabbosta** [comment]
There will also be aarch64 runtime

**Comment by artdeell** [comment]
> There will also be aarch64 runtime?

@gabbosta No, this just adds the ability to install packs using file selector

**Comment by gabbosta** [comment]
Vc sabe mexer bem com programação?

**Comment by gabbosta** [comment]
Se sim eu vou te marcar uma coisa que o @longjunyu2 quer fazer

**Comment by gabbosta** [comment]
#30 he wanted to be able to increase largeHeap to over 1024

**Comment by artdeell** [comment]
> #30 he wanted to be able to increase largeHeap to over 1024

1. Setting the RAM amound for the app via largeHeap is impossible; this option just says to Android:
"Hey, I need more heap RAM!"
2. The inability to set more than 1024 megs of RAM is because 32-bit Java VM i think.
It's like a Windows with 32-bit Java: you just can't set more than 1.5 gigs of RAM or the VM will crash.

**Comment by gabbosta** [comment]
then there is a solution, if so which one?

**Comment by gabbosta** [comment]
hey what is the first two options for global settings advanced

**Comment by artdeell** [comment]
Build JDK for AArch64
I couldn't see any more ways.

**Comment by gabbosta** [comment]
I don't have a computer

**Comment by artdeell** [comment]
I will try to do it. Hope it will work.

**Comment by gabbosta** [comment]
JDK 8?

**Comment by artdeell** [comment]
> JDK 8?

JDK 8.

**Comment by gabbosta** [comment]
Thank you very much, you are very nice, when you can send me here to test pfv

**Comment by artdeell** [comment]
I don't know. First I need to try, it may not succeed

**Comment by gabbosta** [comment]
Ok thank Very mech

**Comment by gabbosta** [comment]
Are you trying?

**Comment by gabbosta** [comment]
I found an aarch64 jdk8: https://github.com/AdoptOpenJDK/openjdk-aarch64-jdk8u

**Comment by gabbosta** [comment]
What to do now

**Comment by artdeell** [comment]
https://openjdk.java.net/projects/aarch64-port/

**Comment by artdeell** [comment]
Attempting to build this

**Comment by artdeell** [comment]
@longjunyu2 please review

**Comment by LegacyGamerHD** [comment]
@artdeell any news on jdk aarch64

**Comment by longjunyu2** [comment]
wow,big commits!

**Pull request merged**
